# Generated by Django 5.0.3 on 2024-03-31 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_baseprofile_cv_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='cv_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
